Name:           ros-jade-simple-grasping
Version:        0.2.2
Release:        0%{?dist}
Summary:        ROS simple_grasping package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/simple_grasping
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-actionlib
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-grasping-msgs
Requires:       ros-jade-message-runtime
Requires:       ros-jade-moveit-msgs
Requires:       ros-jade-moveit-python
Requires:       ros-jade-pcl-ros
Requires:       ros-jade-roscpp
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-shape-msgs
Requires:       ros-jade-tf
BuildRequires:  ros-jade-actionlib
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cmake-modules
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-grasping-msgs
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-moveit-msgs
BuildRequires:  ros-jade-pcl-ros
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-shape-msgs
BuildRequires:  ros-jade-tf

%description
Basic grasping applications and demos.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Aug 23 2016 Michael Ferguson <mferguson@fetchrobotics.com> - 0.2.2-0
- Autogenerated by Bloom

